from matplotlib import image

from src.phase02.ex01.monochromatic.monochromatic_cipher import monochromatic_cipher, mono_cipher


def monochromatic_decipher(input_file, output_file, rect, key):
    """
    Deciphers an image using a monochromatic cipher.

    :param input_file: the input image file to decipher
    :param output_file: the output image file to write the deciphered image to
    :param rect: the rectangular region of the image to decipher (in the format [top, bottom, left, right])
    :param key: the cipher key, previously generated by the cipher
    """

    img = image.imread(input_file)

    mono_cipher(img, output_file, rect, key)


# Cipher and decipher lena.bmp
if __name__ == '__main__':
    rectangular_region = (0.2, 0.2, 0.2, 0.2)

    cipher_key = monochromatic_cipher('lena.bmp', 'lena_cipher.bmp', rectangular_region)

    monochromatic_decipher('lena_cipher.bmp', 'lena_decipher.bmp', rectangular_region, cipher_key)
